image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # добавления прав на запуск файла gradlew
  - chmod +x gradlew
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов). В данной задаче запуск SUT не нужен.
  #- java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации